CREATE TABLE user(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    tiempo DECIMAL(9,2) NOT NULL,
    encargado VARCHAR(255) NOT NULL
);